#spring
spring:
  application:
    name: app-web
  profiles:
    active: "@activatedProperties@"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 15
      max-wait: 60000 #缺省使用公平锁
      min-idle: 1 #最小连接池数量
      max-evictable-idle-time-millis: 600000 #连接最大生存时间, ms
      min-evictable-idle-time-millis: 300000 #连接最小生存时间, ms，默认300s
      test-on-borrow: false
      test-on-return: false #默认值,不配置
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 10000
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
#mybatis-plus配置
mybatis-plus:
  configuration:
    auto-mapping-behavior: FULL
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: "now()"
      logic-not-delete-value: "'1970-01-01 08:00:01'"
#log
logging:
  config: classpath:log4j2.xml
log:
  enabled: true