server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/code_helper?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl